In [1]:
import numpy as np

In [2]:
arr =np.array([1, 2, 3, 4, 5])

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
# 2차원 벡터 5x5 배열을 만들어 0으로 초기화 해준다. 혹시 모를 이전의 흔적을 지우기 위함이다.
arr = np.zeros((5, 5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
# 빈 값으로 만들어진 2차원 벡터 3x3 배열 만들기
arr = np.empty((3, 3))
print(arr)

[[5.00384925e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [7]:
# 1로 되어 있는 3x3 배열 만들기
arr = np.ones((3, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# 배열 생성하기. 0부터 "()안의 숫자 -1"까지 생성
arr = np.arange(8)
print(arr)

[0 1 2 3 4 5 6 7]


In [9]:
# ndarray 배열의 모양 확인하기
arr = np.array([[3, 5, 8], [2, 5, 4]])
print(arr.shape)

(2, 3)


In [10]:
# ndarray 차원 확인하기
print(arr.ndim)

2


In [11]:
# ndarray 데이터 타입 확인하기
print(arr.dtype)

int64


In [12]:
# 형변환. float 크기가 클수록 표현할 수 있는 양이 많아진다.
arr_float = arr.astype(np.float64)
print(arr_float.dtype)

float64


In [13]:
# 문자열
arr_str = np.array(['1', '2', '3'])
print(arr_str.dtype)

<U1


In [14]:
# 정수형
arr_int = arr_str.astype(np.int64)
print(arr_int.dtype)

int64


In [15]:
# 배열의 연산

# 덧셈
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1 + arr2)
print(np.add(arr1, arr2))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [16]:
# 곱셈
print(arr1 * arr2)
print(np.multiply(arr1, arr2))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [17]:
# ndarray 배열 슬라이싱
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr_1 = arr[:2, 1:3]
print(arr_1)

[[2 3]
 [5 6]]


In [18]:
print(arr[0, 2])

3


In [19]:
print(arr[[0, 1 ,2],[2, 0, 1]])
idx = arr > 3
print(idx)

[3 4 8]
[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [20]:
print(arr[idx])

[4 5 6 7 8 9]


In [24]:
# NumPy 레드와인 데이터 실습

# 첫줄은 헤더니깐 건너뛰고, 구별자(delimiter)는 ','로 한다.
redwine = np.loadtxt(fname='winequality-red.csv', delimiter=',', skiprows=1)
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [25]:
# 전체 데이터의 합계
print(redwine.sum())

152084.78194


In [26]:
# 평균
print(redwine.mean())


7.926036165311652


In [30]:
# 0번 축 기준 합계(각 칼럼의 합계)
print(redwine.sum(axis=0))

[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]


In [31]:
# 0번 축 기준 평균(각 칼럼의 평균)
print(redwine.mean(axis=0))

[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [39]:
# 이제 슬라이싱을 해 본다. :은 전체 데이터를 의미. 0은 제일 첫 번째 컬럼을 의미 fixed acid 항목 나옴
print(redwine[:, 0])

[7.4 7.8 7.8 ... 6.3 5.9 6. ]


In [40]:
#  첫 번째 칼럼의 평균
print(redwine[:,0].mean())

8.31963727329581


In [41]:
# 각 칼럼 당 max값 찾기. 가장 좋은 퀄리티:72, 도수 가장 높은 것:14.9...
print(redwine.max(axis=0))

[ 15.9       1.58      1.       15.5       0.611    72.      289.
   1.00369   4.01      2.       14.9       8.     ]


In [42]:
# 각 칼럼 당 min값 찾기. 가장 낮은 퀄리티: 3, 도수 가장 낮은 것: 8.4...
print(redwine.min(axis=0))

[4.6     0.12    0.      0.9     0.012   1.      6.      0.99007 2.74
 0.33    8.4     3.     ]
